### ISSUE TITLE
Exception during run in Narsil

### ISSUE THREAD

**Issue by uecasm** [Synthesis-Collective/speedandreachfixes#6]
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ProcessNullTermination(ReadOnlySpan`1 bytes)
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ProcessWholeToZString(ReadOnlySpan`1 bytes)
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ParsePrependedString(ReadOnlyMemorySlice`1 span, Byte lengthLength)
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureBinaryOverlay.get_Name()
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureSetterTranslationCommon.DeepCopyIn(IAlternateTexture item, IAlternateTextureGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureSetterTranslationCommon.DeepCopy(IAlternateTextureGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.AlternateTextureMixIn.DeepCopy(IAlternateTextureGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.<>c__DisplayClass1_0.<DeepCopyIn>b__0(IAlternateTextureGetter r)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Noggog.ExtendedList`1..ctor(IEnumerable`1 collection) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Containers\ExtendedList.cs:line 16
   at Noggog.EnumerableExt.ToExtendedList[T](IEnumerable`1 e) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 277
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.DeepCopyIn(IModel item, IModelGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.DeepCopy(IModelGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.ModelMixIn.DeepCopy(IModelGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopyIn(IWeapon item, IWeaponGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopyIn(IWeaponInternal item, IWeaponGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopy(IWeaponGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.Skyrim.WeaponMixIn.DeepCopy(IWeaponGetter item, TranslationMask copyMask)
   at SpeedandReachFixes.Program.RunPatch(IPatcherState`2 state) in C:\Temp\Synthesis\db39db1f-8085-484d-a161-6461b1814a0b\Git\ae41e5f7-0a57-43a1-aee6-9de693293890\Runner\SpeedandReachFixes\Program.cs:line 64
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
```

**Comment by Noggog** [comment]
I just pushed a small update.  Restart synth, and make sure your speed and reach fixes look like this:
![image](https://user-images.githubusercontent.com/24981326/134433765-0f50be09-d008-4ffe-9758-6c00a90ea8a4.png)

Important part is making sure it's using the `6dfa0f0` commit

Run it again, and it should print out more information on what record specifically it's having trouble with

**Comment by uecasm** [comment]
```
Successfully modified weapon: CYREnchIronBattleaxeSoulTrap03
RecordException  => WarLongBow (0013D9:ArcheryV2.esp<Weapon>): Index was outside the bounds of the array. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ProcessNullTermination(ReadOnlySpan`1 bytes)
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ProcessWholeToZString(ReadOnlySpan`1 bytes)
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ParsePrependedString(ReadOnlyMemorySlice`1 span, Byte lengthLength)
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureBinaryOverlay.get_Name()
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureSetterTranslationCommon.DeepCopyIn(IAlternateTexture item, IAlternateTextureGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureSetterTranslationCommon.DeepCopy(IAlternateTextureGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.AlternateTextureMixIn.DeepCopy(IAlternateTextureGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.<>c__DisplayClass1_0.<DeepCopyIn>b__0(IAlternateTextureGetter r)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Noggog.ExtendedList`1..ctor(IEnumerable`1 collection) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Containers\ExtendedList.cs:line 16
   at Noggog.EnumerableExt.ToExtendedList[T](IEnumerable`1 e) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 277
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.DeepCopyIn(IModel item, IModelGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.DeepCopy(IModelGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.ModelMixIn.DeepCopy(IModelGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopyIn(IWeapon item, IWeaponGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopyIn(IWeaponInternal item, IWeaponGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.WeaponSetterTranslationCommon.DeepCopy(IWeaponGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.Skyrim.WeaponMixIn.DeepCopy(IWeaponGetter item, TranslationMask copyMask)
   at SpeedandReachFixes.Program.RunPatch(IPatcherState`2 state) in C:\Temp\Synthesis\db39db1f-8085-484d-a161-6461b1814a0b\Git\ae41e5f7-0a57-43a1-aee6-9de693293890\Runner\SpeedandReachFixes\Program.cs:line 77   at SpeedandReachFixes.Program.RunPatch(IPatcherState`2 state) in C:\Temp\Synthesis\db39db1f-8085-484d-a161-6461b1814a0b\Git\ae41e5f7-0a57-43a1-aee6-9de693293890\Runner\SpeedandReachFixes\Program.cs:line 99
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Successfully modified weapon: CYREnchIronBattleaxeStamina01
```

**Comment by Noggog** [comment]
Do you have a link to the mod `ArcheryV2.esp`?
Edit: I think i found it

**Comment by Noggog** [comment]
Cool!  Fix pushed up.  
https://github.com/Mutagen-Modding/Mutagen/commit/4cc79a5af1d4992b597916ee0951b48f5af93c59

Pushed it up as Mutagen `v0.31.1-prerelease008`

Can upgrade your patcher to use the newest synth/mutagen versions and see how it goes!  Click the prereleases checkbox in your profile settings at the top bar
![image](https://user-images.githubusercontent.com/24981326/134439312-7dfd0f92-cf88-458c-b017-a44f649b2380.png)

**Comment by uecasm** [comment]
Thanks for the quick fix -- seems to run fine now.
